### ISSUE TITLE
Fix SVG icon

### ISSUE THREAD

**Issue by dshanske** [dshanske/simple-location#11]
Fix display of SVG icon.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/simple-location/issues/11" class="u-in-reply-to"></a>I know this was fixed in a prior version, but it looks like it's slipped back in again in v3.0.2?

Perhaps it was fixed in one of the dev versions I downloaded from Github, but it's not in the production version on WordPress.org at the moment.

**Comment by dshanske** [comment]
Odd. Will check the code.

**Comment by dshanske** [comment]
Found it. The new CSS files did not end up in the tracked files for the SVN. Will update.
